Bug ticks
d3plus/d3plus-timeline pull request #33
Opened 2018-09-10 18:59 UTC by cnavarreteliz

(closes d3plus/d3plus-viz#94)

### Description
The bug was caused because the current behavior in button timeline only accepted correlatives values. For to solve it, I set the buttonBehavior with ordinal scale, and I rewrite the logic behind selections and domains using buttons. 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

2018-09-11 14:03 UTC, davelandry requested changes

2018-09-11 14:03 UTC, davelandry commented on src/Timeline.js
> +    this._align = () => this._buttonBehaviorCurrent === "buttons" ? "middle" : "start";
why is this here? shouldn't this just be the default d3plus-axis `"middle"` for all button types?

2018-09-11 14:03 UTC, davelandry commented on src/Timeline.js
> +      const domain = this._buttonBehaviorCurrent === "ticks"
this logic of determining the `pixelDomain` is getting rather large, and being used in 3 places. move this code out of these 3 functions into it's on method of the class called `_pixelDomain`

2018-09-11 14:03 UTC, davelandry commented on src/Timeline.js
> +          : [new Date(this._availableTicks[ticks.indexOf(domain[0])], 0, 1), new Date(this._availableTicks[ticks.indexOf(domain[1])], 0, 1)];
why are you using the JavaScript `Date` and not the d3plus `date` function? You can probably just use `date` and condense all of this code.

2018-09-12 14:43 UTC, davelandry requested changes

2018-09-12 14:43 UTC, davelandry commented on src/Timeline.js
> +          : [event.sourceEvent.offsetX, event.sourceEvent.offsetX]).map(Number);
can we move these `domain` and `ticks` variables into the updateDomain function as well?

2018-09-12 15:21 UTC, cnavarreteliz commented on src/Timeline.js
> +          : [event.sourceEvent.offsetX, event.sourceEvent.offsetX]).map(Number);
I tried it yesterday and I had problems, because in every event the calcule of the domain is different, and `ticks` variable is used for to calculate `this._selection` when buttonBehavior is `button`.

2018-09-13 15:24 UTC, davelandry requested changes

2018-09-13 15:24 UTC, davelandry commented on src/Timeline.js
> +          : [event.sourceEvent.offsetX, event.sourceEvent.offsetX]).map(Number);
The only difference in the `domain` variables that I see is in the `_brushBrush` event where you override the `selection` to be used. Could that logic be applied directly in the `_updateDomain` function? If not, could it be applied to the domain after running the `_updateDomain` function? You are currently returning `domain` from that function, but are not catching it (just updating the domain in place). I could see something like this:

```js
const domain = this._updateDomain(event);
```

Additionally, you can move the `ticks` variable into that function (you already have it in there!) and just return that as well as part of an Object that you can destructure:

```js
return {domain, ticks};
```

```js
const {domain, ticks} = this._updateDomain(event);
```

2018-09-14 16:34 UTC, davelandry requested changes
Found two small bugs with the latest build:

1. On non-brushing timelines, the padding/spacing is off (look at the highlighted area):

![spacing](https://user-images.githubusercontent.com/1847581/45563127-69e3d700-b81a-11e8-9a91-e01bcdfd4e99.gif)

2. On brushing timelines, the selection is wrong if you start brushing on the right side of the button:

![brushing](https://user-images.githubusercontent.com/1847581/45563144-7bc57a00-b81a-11e8-88ad-6e1c8d80a87a.gif)

2018-09-14 16:34 UTC, davelandry commented on src/Timeline.js
> +    this._align = "middle";
this is duplicating the default inside of `Axis`, so it can be removed.

2018-09-14 18:46 UTC, cnavarreteliz commented
![bug](https://user-images.githubusercontent.com/5233593/45569210-3498b280-b835-11e8-8a27-40387b13921f.gif)
I didn't can reproduce the first bug in my laptop.

I identified the root cause of the second bug, and I'm working on it!

2018-09-17 14:14 UTC, davelandry commented
What browser are you using? I'm able to see the first bug in both Chrome and Safari. Can you post a screenshot of what you see?

2018-09-17 14:23 UTC, cnavarreteliz commented
![d3plusbug](https://user-images.githubusercontent.com/5233593/45629072-ec170a00-ba6b-11e8-996d-0439d7b9e60a.gif)

@davelandry I tested in Safari and Chrome without problems.

*Google Chrome | 68.0.3440.106 (Build oficial) (64 bits)*

2018-09-17 16:53 UTC, davelandry approved these changes

2018-09-17 16:53 UTC, merged

2018-09-17 17:21 UTC, davelandry commented
@cnavarreteliz I just did a release, can you check to see if you can see the bug with the production build? https://d3plus.org/js/d3plus-timeline.v0.4.full.min.js