solves weird behavior in button widths
d3plus/d3plus-timeline pull request #37
Opened 2018-09-19 22:14 UTC by cnavarreteliz

closes #36 

### Description

This bug was caused because the logic behind of `x position` in Axis.js was calculated with `this._padding` and in Timeline buttons we were using `this._buttonPadding`.

For to solve it, I deleted `this._buttonPadding`, and now we're using `this._padding`. The only additional thing that I had to make was set a minimal value of padding in buttons.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

2018-09-20 16:08 UTC, davelandry requested changes
This doesn't fix it for me. Additionally, we shouldn't be using/overriding `this._padding`, as that variable is used for the outer padding around the timeline.

<img width="187" alt="screen shot 2018-09-20 at 12 07 08 pm" src="https://user-images.githubusercontent.com/1847581/45831602-cf7a0c80-bccd-11e8-99db-2997b75f7f99.png">

2018-09-20 20:16 UTC, cnavarreteliz commented
Seeing the bug, I identified that the problem only occurred when `.align("middle")` :) So, I deleted an unnecessary variable of marginLeft

2018-09-21 14:30 UTC, davelandry requested changes
Looking good! However, please do not use `this._padding` for the internal button padding. This variable is used in d3plus-axis for the padding around the entire axis. Just add back in your `buttonPadding` variable for your purpose.

2018-09-24 15:42 UTC, davelandry requested changes
looking great! found 1 small bug: sizing does not work when setting `.align("start")`:

<img width="175" alt="screen shot 2018-09-24 at 11 41 44 am" src="https://user-images.githubusercontent.com/1847581/45962490-f6e31900-bfee-11e8-9def-5c1ffdac2cce.png">

```js
const timeline = new d3plus.Timeline()
  .align("start")
  .domain([2001, 2004])
  .ticks([2001, 2002, 2003, 2004])
  .render();
```

2018-09-24 20:06 UTC, merged