button timeline working with Date objects
d3plus/d3plus-timeline pull request #38
Opened 2018-09-20 00:21 UTC by cnavarreteliz

closes #35 

### Description

I solved this bug adding a test that checks if the object is Date.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

2018-09-20 16:13 UTC, davelandry requested changes
This solution will only work if the timeline is for years, but will break for thinks like month and day intervals. Have you tried simply setting `this._tickFormat` based on the variable you use for the tick widths?

2018-09-21 14:24 UTC, davelandry requested changes

2018-09-21 14:24 UTC, davelandry commented on src/Timeline.js
> +    if (this._ticks) this._ticks = this._ticks.map(this._dateToString);
I don't understand this logic. 2 lines below this you transform the ticks back into dates anyways and create a tickFormat variable there.

2018-09-24 13:57 UTC, cnavarreteliz commented on src/Timeline.js
> +    if (this._ticks) this._ticks = this._ticks.map(this._dateToString);
`let ticks = this._ticks ? this._ticks.map(date) : this._domain.map(date);` and `tickFormat` they're for to calculate internally the width of the buttons.

The goal of `if (this._ticks) this._ticks = this._ticks.map(this._dateToString);` is to standardize the ticks passed by the user.

2018-09-24 15:37 UTC, davelandry requested changes

2018-09-24 15:37 UTC, davelandry commented on src/Timeline.js
> +    if (this._ticks) this._ticks = this._ticks.map(this._dateToString);
Right, but `tickFormat` you create in `_dateToString` does not use the domain and range, so it's tick formatter is actually different than the one you use for the width. The d3 time formatter takes the available space and domain of the data into account when suggesting a formatter.

I did a little investigation, and simply adding this one line to line #244 solve the bug for me:

```js
if (!this._tickFormat) this._tickFormat = tickFormat;
```

2018-09-24 15:38 UTC, davelandry commented
The issue is happening because internally in d3plus-axis it knows to use a date formatter if the scale type if "time", but in our case of buttons we need to use "ordinal".

2018-09-24 19:28 UTC, davelandry requested changes
I'm getting an error when using this latest code:

```js
function toDate(d) {
  const date = new Date(`${d}/01/01`);
  date.setFullYear(d);
  return date;
}

const timeline = new d3plus.Timeline()
  .domain([2001, 2004].map(toDate))
  .ticks([2001, 2002, 2003, 2004].map(toDate))
  .render();
```

2018-09-24 19:35 UTC, cnavarreteliz commented
@davelandry I'm working in this bug. It's caused here: `Array.from(Array(this._domain[1] - this._domain[0] + 1), (_, x) => this._domain[0] + x)` when you pass a Date in the domain. But the rest of the simplification in the code it's working fine.

2018-09-24 20:30 UTC, davelandry approved these changes

2018-09-24 20:30 UTC, davelandry commented
![](https://media3.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif)

2018-09-24 20:31 UTC, davelandry commented
@cnavarreteliz can you resolve the conflicts?

2018-09-24 21:48 UTC, cnavarreteliz commented
@davelandry done! This is one of the most happiest days in my life of programmer haha and I think that I learnt so much Javascript with d3plus-timeline.

2018-09-25 16:00 UTC, merged