adds tickSpecified method
d3plus/d3plus-timeline pull request #48
Opened 2018-12-13 12:31 UTC by cnavarreteliz

closes #47 

### Description

This PR fixes the problem of weird render of labels adding a new feature called `tickSpecifier`, that allows customize the tick format. 

This new method uses tickFormat from d3-scale ([https://github.com/d3/d3-scale#time_tickFormat](https://github.com/d3/d3-scale#time_tickFormat)) and also it fixes minor bugs detected, like weird width of timeline with ticks when domain is not defined.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

2018-12-13 22:50 UTC, davelandry requested changes
Move the `tickSpecifier` method definition directly inside of `Axis`!

2018-12-17 16:43 UTC, davelandry requested changes
Seems to break "ticks":

```js
new d3plus.Timeline()
    .buttonBehavior("ticks")
    .brushing(false)
    .domain([2011, 2014])
    .ticks([2011, 2012, 2013, 2014])
    .render();
```

2018-12-17 16:44 UTC, davelandry commented
@cnavarreteliz make sure to pull and `npm i`, I pushed a commit that updates to the latest d3plus-axis

2018-12-17 18:13 UTC, cnavarreteliz commented
@davelandry I just updated `package.json` with the last version of d3plus-axis and It works fine!

2018-12-18 14:29 UTC, davelandry commented
@cnavarreteliz I had already updated `package.json` (see my previous commit), still seeing an error with this chart (I even completely re-installed node modules):

```js
new d3plus.Timeline()
  .buttonBehavior("ticks")
  .domain([2011, 2014])
  .ticks([2011, 2012, 2013, 2014])
  .render();
```

It seems to only happen when I specify `ticks`. Here's the output:

<img width="570" alt="screen shot 2018-12-18 at 9 29 29 am" src="https://user-images.githubusercontent.com/1847581/50160473-73f8f400-02a7-11e9-818f-fb6418022e6e.png">

2018-12-18 17:40 UTC, cnavarreteliz commented
@davelandry can you test if the problem was solved with the last commit?

2018-12-19 18:45 UTC, davelandry commented
👏 well done @cnavarreteliz

2018-12-19 18:45 UTC, davelandry approved these changes

2018-12-19 18:45 UTC, merged