add brushMin config option for "ticks" buttonBehavior
d3plus/d3plus-timeline pull request #70
Opened 2022-07-15 22:04 UTC by davelandry

This PR adds a new `brushMin` method to the Timeline class, which defaults to `1` (the current behavior).

<img width="397" alt="Screen Shot 2022-07-15 at 6 03 33 PM" src="https://user-images.githubusercontent.com/1847581/179317056-b9293ec1-c5a4-470e-b92f-81da9990ed51.png">

```js
const control = new d3plus.Timeline()
  .buttonBehavior("ticks")
  .brushMin(2)
  .domain([2011, 2015])
  .ticks([2011, 2012, 2013, 2014, 2015])
  .render();
```

2022-07-18 16:15 UTC, ffigueroal requested changes

2022-07-18 16:15 UTC, ffigueroal commented on src/Timeline.js
> +        else maxDomain = ticks[maxIndex + 1];
@davelandry since it is possible to change `brushMin` to a value other than 1, I think we should use that value to calculate the domain. Maybe something like this could be useful:
```
if (Math.abs(maxIndex - minIndex) < this._brushMin) {
    if (domain[0] <= domain[1] && minIndex > 0) minDomain = ticks[minIndex - (this._brushMin - Math.abs(maxIndex - minIndex) - 1)];
    else maxDomain = ticks[maxIndex + (this._brushMin - Math.abs(maxIndex - minIndex) - 1)];
}
```

2022-07-19 19:09 UTC, davelandry commented on src/Timeline.js
> +        else maxDomain = ticks[maxIndex + 1];
@ffigueroal some good stuff here. I ended up restructuring the code a bit, taking some of your code and also catching a few more edge cases where I was able to mess up the timeline with some quick/erratic mouse drags. Let me know what you think!

2022-07-19 20:17 UTC, ffigueroal approved these changes

2022-07-19 20:17 UTC, merged